// Get all ice creams
GET http://localhost:3000/api/ice-cream

###

// Get specific ice cream
GET http://localhost:3000/api/ice-cream/2

###

// Add new ice cream
POST http://localhost:3000/api/ice-cream
Content-Type: application/json

{
    "name": "Twister",
    "price": 12,
    "description": "En riktig barnfavorit! Njut av en glass med flertalet populära fruktsmaker såsom ananas, citron och jordgubb.",
    "image": "https://asset-eu.unileversolutions.com/content/dam/unilever/heart/sweden/static_not_in-use_products_/product_only/ice_cream/out_of_home_ice_cream/heartbrand_glasspinne_twister_80_ml/8000920400470_twister-1209715-png.png.ulenscale.600x600.png"
}

###

// Update existing ice cream
PUT http://localhost:3000/api/ice-cream/2
Content-Type: application/json

{
        "name": "Piggelin",
        "price": 8,
        "description": "Härligt läskande slush med smak av favoriten Piggelin!",
        "image": "https://asset-eu.unileversolutions.com/content/dam/unilever/heart/sweden/pack_shot/piggelin-1570534-png.png.ulenscale.600x600.png"
}


###

// Delete ice cream
DELETE http://localhost:3000/api/ice-cream/1